### ISSUE TITLE
Resource Group duplicate error

### ISSUE THREAD

**Issue by stuartort** [Azure-Terraform/terraform-azurerm-resource-group#9]
Working with Godji Fortil to start an instance and using the resource_group definition below, I am getting an error about a resource group existing

module "resource_group" {
  source = "github.com/Azure-Terraform/terraform-azurerm-resource-group.git?ref=v2.0.0"

#  user        = local.admin
  unique_name = true
  location    = module.metadata.location
  names       = module.metadata.names
  tags        = merge(module.metadata.tags, { "admin" : local.admin })
}

-040d-2e0c-6943-d6231d3b9823]
module.kubernetes.azurerm_kubernetes_cluster.aks: Creating...
╷
│ Error: creating Managed Kubernetes Cluster "app-contosoweb-dev-eastus2" (Resource Group "app-contosoweb-dev-eastus2-13858"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="NodeResourceGroupAlreadyExists" Message="Node resource group 'MC_app-contosoweb-dev-eastus2' under subscription 'ec0ba952-4ae9-4f69-b61c-4b96ff470038' already exists, please provide a new one."
│
│   with module.kubernetes.azurerm_kubernetes_cluster.aks,
│   on .terraform/modules/kubernetes/main.tf line 26, in resource "azurerm_kubernetes_cluster" "aks":
│   26: resource "azurerm_kubernetes_cluster" "aks" {
│
╵

**Comment by stuartort** [comment]
@gfortil

**Comment by fabiendelpierre** [comment]
Your issue doesn't have to do with this module. It looks like you're working with AKS, and AKS creates a distinct resource group in which it places resources that it manages directly. AKS is unable to create that resource group because one with the same name already exists. This isn't affected by you having set the `unique_name` variable of this module because this module doesn't control the resource group I'm talking about.

Whether you're using our [opinionated AKS module for Terraform](https://github.com/LexisNexis-RBA/terraform-azurerm-aks/) or our [open-source module](https://github.com/Azure-Terraform/terraform-azurerm-kubernetes), the name of that resource group is controlled by [this line](https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/blob/master/locals.tf#L7).

If you're using the open source module, you can override the name of that resource group by setting the `node_resource_group` variable.

If you're using the opinionated module, you can set the `cluster_name` variable.

**Comment by stuartort** [comment]
Closing this issue
